/PROG  H001.LS
/ATTR
OWNER       = MNEDITOR;
COMMENT     = "";
PROG_SIZE   = 636;
CREATE      = DATE 23-01-07  TIME 11:59:14;
MODIFIED    = DATE 23-01-07  TIME 12:02:18;
FILE_NAME   = ;
VERSION     = 0;
LINE_COUNT  = 4;
MEMORY_SIZE = 992;
PROTECT     = READ_WRITE;
TCD:  STACK_SIZE    = 0,
      TASK_PRIORITY = 50,
      TIME_SLICE    = 0,
      BUSY_LAMP_OFF = 0,
      ABORT_REQUEST = 0,
      PAUSE_REQUEST = 0;
DEFAULT_GROUP    = 1,*,*,*,*;
CONTROL_CODE     = 00000000 00000000;
/MN
   1:J P[1] 100% FINE    ;
   2:L P[2] 100mm/sec CNT100    ;
   3:L P[3] 100mm/sec CNT100    ;
   4:L P[4] 100mm/sec CNT100    ;
   5:L P[5] 100mm/sec CNT100    ;
   6:L P[6] 100mm/sec CNT100    ;
   7:L P[7] 100mm/sec CNT100    ;
   8:L P[8] 100mm/sec CNT100    ;
   9:L P[9] 100mm/sec CNT100    ;
   10:L P[10] 100mm/sec CNT100    ;
   11:L P[11] 100mm/sec CNT100    ;
   12:L P[12] 100mm/sec CNT100    ;
   13:L P[13] 100mm/sec CNT100    ;
   14:L P[14] 100mm/sec CNT100    ;
   15:L P[15] 100mm/sec CNT100    ;
   16:L P[16] 100mm/sec CNT100    ;
   17:L P[17] 100mm/sec CNT100    ;
   18:L P[18] 100mm/sec CNT100    ;
   19:L P[19] 100mm/sec CNT100    ;
   20:L P[20] 100mm/sec CNT100    ;
   21:L P[21] 100mm/sec CNT100    ;
   22:L P[22] 100mm/sec CNT100    ;
   23:L P[23] 100mm/sec CNT100    ;
   24:L P[24] 100mm/sec CNT100    ;
   25:L P[25] 100mm/sec CNT100    ;
   26:L P[26] 100mm/sec CNT100    ;
   27:L P[27] 100mm/sec CNT100    ;
   28:L P[28] 100mm/sec CNT100    ;
   29:L P[29] 100mm/sec CNT100    ;
   30:L P[30] 100mm/sec CNT100    ;
   31:L P[31] 100mm/sec CNT100    ;
   32:L P[32] 100mm/sec CNT100    ;
   33:L P[33] 100mm/sec CNT100    ;
   34:L P[34] 100mm/sec CNT100    ;
   35:L P[35] 100mm/sec CNT100    ;
   36:L P[36] 100mm/sec CNT100    ;
   37:L P[37] 100mm/sec CNT100    ;
   38:L P[38] 100mm/sec CNT100    ;
   39:L P[39] 100mm/sec CNT100    ;
   40:L P[40] 100mm/sec CNT100    ;
   41:L P[41] 100mm/sec CNT100    ;
   42:L P[42] 100mm/sec CNT100    ;
   43:L P[43] 100mm/sec CNT100    ;
   44:L P[44] 100mm/sec CNT100    ;
   45:L P[45] 100mm/sec CNT100    ;
   46:L P[46] 100mm/sec CNT100    ;
   47:L P[47] 100mm/sec CNT100    ;
   48:L P[48] 100mm/sec CNT100    ;
   49:L P[49] 100mm/sec CNT100    ;
   50:L P[50] 100mm/sec CNT100    ;
   51:L P[51] 100mm/sec CNT100    ;
   52:L P[52] 100mm/sec CNT100    ;
   53:L P[53] 100mm/sec CNT100    ;
   54:L P[54] 100mm/sec CNT100    ;
   55:L P[55] 100mm/sec CNT100    ;
   56:L P[56] 100mm/sec CNT100    ;
   57:L P[57] 100mm/sec CNT100    ;
   58:L P[58] 100mm/sec CNT100    ;
   59:L P[59] 100mm/sec CNT100    ;
   60:L P[60] 100mm/sec CNT100    ;
   61:L P[61] 100mm/sec CNT100    ;
   62:L P[62] 100mm/sec CNT100    ;
   63:L P[63] 100mm/sec CNT100    ;
   64:L P[64] 100mm/sec CNT100    ;
   65:L P[65] 100mm/sec CNT100    ;
   66:L P[66] 100mm/sec CNT100    ;
   67:L P[67] 100mm/sec CNT100    ;
   68:L P[68] 100mm/sec CNT100    ;
   69:L P[69] 100mm/sec CNT100    ;
   70:L P[70] 100mm/sec CNT100    ;
   71:L P[71] 100mm/sec CNT100    ;
   72:L P[72] 100mm/sec CNT100    ;
   73:L P[73] 100mm/sec CNT100    ;
   74:L P[74] 100mm/sec CNT100    ;
   75:L P[75] 100mm/sec CNT100    ;
   76:L P[76] 100mm/sec CNT100    ;
   77:L P[77] 100mm/sec CNT100    ;
   78:L P[78] 100mm/sec CNT100    ;
   79:L P[79] 100mm/sec CNT100    ;
   80:L P[80] 100mm/sec CNT100    ;
   81:L P[81] 100mm/sec CNT100    ;
   82:L P[82] 100mm/sec CNT100    ;
   83:L P[83] 100mm/sec CNT100    ;
   84:L P[84] 100mm/sec CNT100    ;
   85:L P[85] 100mm/sec CNT100    ;
   86:L P[86] 100mm/sec CNT100    ;
   87:L P[87] 100mm/sec CNT100    ;
   88:L P[88] 100mm/sec CNT100    ;
   89:L P[89] 100mm/sec CNT100    ;
   90:L P[90] 100mm/sec CNT100    ;
   91:L P[91] 100mm/sec CNT100    ;
   92:L P[92] 100mm/sec CNT100    ;
   93:L P[93] 100mm/sec CNT100    ;
   94:L P[94] 100mm/sec CNT100    ;
   95:L P[95] 100mm/sec CNT100    ;
   96:L P[96] 100mm/sec CNT100    ;
   97:L P[97] 100mm/sec CNT100    ;
   98:L P[98] 100mm/sec CNT100    ;
   99:L P[99] 100mm/sec CNT100    ;
   100:L P[100] 100mm/sec CNT100    ;
   101:L P[101] 100mm/sec CNT100    ;
   102:L P[102] 100mm/sec CNT100    ;
   103:L P[103] 100mm/sec CNT100    ;
   104:L P[104] 100mm/sec CNT100    ;
   105:L P[105] 100mm/sec CNT100    ;
   106:L P[106] 100mm/sec CNT100    ;
   107:L P[107] 100mm/sec CNT100    ;
   108:L P[108] 100mm/sec CNT100    ;
   109:L P[109] 100mm/sec CNT100    ;
   110:L P[110] 100mm/sec CNT100    ;
   111:L P[111] 100mm/sec CNT100    ;
   112:L P[112] 100mm/sec CNT100    ;
   113:L P[113] 100mm/sec CNT100    ;
   114:L P[114] 100mm/sec CNT100    ;
   115:L P[115] 100mm/sec CNT100    ;
   116:L P[116] 100mm/sec CNT100    ;
   117:L P[117] 100mm/sec CNT100    ;
   118:L P[118] 100mm/sec CNT100    ;
   119:L P[119] 100mm/sec CNT100    ;
   120:L P[120] 100mm/sec CNT100    ;
   121:L P[121] 100mm/sec CNT100    ;
   122:L P[122] 100mm/sec CNT100    ;
   123:L P[123] 100mm/sec CNT100    ;
   124:L P[124] 100mm/sec CNT100    ;
   125:L P[125] 100mm/sec CNT100    ;
   126:L P[126] 100mm/sec CNT100    ;
   127:L P[127] 100mm/sec CNT100    ;
   128:L P[128] 100mm/sec CNT100    ;
   129:L P[129] 100mm/sec CNT100    ;
   130:L P[130] 100mm/sec CNT100    ;
   131:L P[131] 100mm/sec CNT100    ;
   132:L P[132] 100mm/sec CNT100    ;
   133:L P[133] 100mm/sec CNT100    ;
   134:L P[134] 100mm/sec CNT100    ;
   135:L P[135] 100mm/sec CNT100    ;
   136:L P[136] 100mm/sec CNT100    ;
   137:L P[137] 100mm/sec CNT100    ;
   138:L P[138] 100mm/sec CNT100    ;
   139:L P[139] 100mm/sec CNT100    ;
   140:L P[140] 100mm/sec CNT100    ;
   141:L P[141] 100mm/sec CNT100    ;
   142:L P[142] 100mm/sec CNT100    ;
   143:L P[143] 100mm/sec CNT100    ;
   144:L P[144] 100mm/sec CNT100    ;
   145:L P[145] 100mm/sec CNT100    ;
   146:L P[146] 100mm/sec CNT100    ;
   147:L P[147] 100mm/sec CNT100    ;
   148:L P[148] 100mm/sec CNT100    ;
   149:L P[149] 100mm/sec CNT100    ;
   150:L P[150] 100mm/sec CNT100    ;
   151:L P[151] 100mm/sec CNT100    ;
   152:L P[152] 100mm/sec CNT100    ;
   153:L P[153] 100mm/sec CNT100    ;
   154:L P[154] 100mm/sec CNT100    ;
   155:L P[155] 100mm/sec CNT100    ;
   156:L P[156] 100mm/sec CNT100    ;
   157:L P[157] 100mm/sec CNT100    ;
   158:L P[158] 100mm/sec CNT100    ;
   159:L P[159] 100mm/sec CNT100    ;
   160:L P[160] 100mm/sec CNT100    ;
   161:L P[161] 100mm/sec CNT100    ;
   162:L P[162] 100mm/sec CNT100    ;
   163:L P[163] 100mm/sec CNT100    ;
   164:L P[164] 100mm/sec CNT100    ;
   165:L P[165] 100mm/sec CNT100    ;
   166:L P[166] 100mm/sec CNT100    ;
   167:L P[167] 100mm/sec CNT100    ;
   168:L P[168] 100mm/sec CNT100    ;
   169:L P[169] 100mm/sec CNT100    ;
   170:L P[170] 100mm/sec CNT100    ;
   171:L P[171] 100mm/sec CNT100    ;
   172:L P[172] 100mm/sec CNT100    ;
   173:L P[173] 100mm/sec CNT100    ;
   174:L P[174] 100mm/sec CNT100    ;
   175:L P[175] 100mm/sec CNT100    ;
   176:L P[176] 100mm/sec CNT100    ;
   177:L P[177] 100mm/sec CNT100    ;
   178:L P[178] 100mm/sec CNT100    ;
   179:L P[179] 100mm/sec CNT100    ;
   180:L P[180] 100mm/sec CNT100    ;
   181:L P[181] 100mm/sec CNT100    ;
   182:L P[182] 100mm/sec CNT100    ;
   183:L P[183] 100mm/sec CNT100    ;
   184:L P[184] 100mm/sec CNT100    ;
   185:L P[185] 100mm/sec CNT100    ;
   186:L P[186] 100mm/sec CNT100    ;
   187:L P[187] 100mm/sec CNT100    ;
   188:L P[188] 100mm/sec CNT100    ;
   189:L P[189] 100mm/sec CNT100    ;
   190:L P[190] 100mm/sec CNT100    ;
   191:L P[191] 100mm/sec CNT100    ;
   192:L P[192] 100mm/sec CNT100    ;
   193:L P[193] 100mm/sec CNT100    ;
   194:L P[194] 100mm/sec CNT100    ;
   195:L P[195] 100mm/sec CNT100    ;
   196:L P[196] 100mm/sec CNT100    ;
   197:L P[197] 100mm/sec CNT100    ;
   198:L P[198] 100mm/sec CNT100    ;
   199:L P[199] 100mm/sec CNT100    ;
   200:L P[200] 100mm/sec CNT100    ;
   201:L P[201] 100mm/sec CNT100    ;
   202:L P[202] 100mm/sec CNT100    ;
   203:L P[203] 100mm/sec CNT100    ;
   204:L P[204] 100mm/sec CNT100    ;
   205:L P[205] 100mm/sec CNT100    ;
   206:L P[206] 100mm/sec CNT100    ;
   207:L P[207] 100mm/sec CNT100    ;
   208:L P[208] 100mm/sec CNT100    ;
   209:L P[209] 100mm/sec CNT100    ;
   210:L P[210] 100mm/sec CNT100    ;
   211:L P[211] 100mm/sec CNT100    ;
   212:L P[212] 100mm/sec CNT100    ;
   213:L P[213] 100mm/sec CNT100    ;
   214:L P[214] 100mm/sec CNT100    ;
   215:L P[215] 100mm/sec CNT100    ;
   216:L P[216] 100mm/sec CNT100    ;
   217:L P[217] 100mm/sec CNT100    ;
   218:L P[218] 100mm/sec CNT100    ;
   219:L P[219] 100mm/sec CNT100    ;
   220:L P[220] 100mm/sec CNT100    ;
   221:L P[221] 100mm/sec CNT100    ;
   222:L P[222] 100mm/sec CNT100    ;
   223:L P[223] 100mm/sec CNT100    ;
   224:L P[224] 100mm/sec CNT100    ;
   225:L P[225] 100mm/sec CNT100    ;
   226:L P[226] 100mm/sec CNT100    ;
   227:L P[227] 100mm/sec CNT100    ;
   228:L P[228] 100mm/sec CNT100    ;
   229:L P[229] 100mm/sec CNT100    ;
   230:L P[230] 100mm/sec CNT100    ;
   231:L P[231] 100mm/sec CNT100    ;
   232:L P[232] 100mm/sec CNT100    ;
   233:L P[233] 100mm/sec CNT100    ;
   234:L P[234] 100mm/sec CNT100    ;
   235:L P[235] 100mm/sec CNT100    ;
   236:L P[236] 100mm/sec CNT100    ;
   237:L P[237] 100mm/sec CNT100    ;
   238:L P[238] 100mm/sec CNT100    ;
   239:L P[239] 100mm/sec CNT100    ;
   240:L P[240] 100mm/sec CNT100    ;
   241:L P[241] 100mm/sec CNT100    ;
   242:L P[242] 100mm/sec CNT100    ;
   243:L P[243] 100mm/sec CNT100    ;
   244:L P[244] 100mm/sec CNT100    ;
   245:L P[245] 100mm/sec CNT100    ;
   246:L P[246] 100mm/sec CNT100    ;
   247:L P[247] 100mm/sec CNT100    ;
   248:L P[248] 100mm/sec CNT100    ;
   249:L P[249] 100mm/sec CNT100    ;
   250:L P[250] 100mm/sec CNT100    ;
   251:L P[251] 100mm/sec CNT100    ;
   252:L P[252] 100mm/sec CNT100    ;
   253:L P[253] 100mm/sec CNT100    ;
   254:L P[254] 100mm/sec CNT100    ;
   255:L P[255] 100mm/sec CNT100    ;
   256:L P[256] 100mm/sec CNT100    ;
   257:L P[257] 100mm/sec CNT100    ;
   258:L P[258] 100mm/sec CNT100    ;
   259:L P[259] 100mm/sec CNT100    ;
   260:L P[260] 100mm/sec CNT100    ;
   261:L P[261] 100mm/sec CNT100    ;
   262:L P[262] 100mm/sec CNT100    ;
   263:L P[263] 100mm/sec CNT100    ;
   264:L P[264] 100mm/sec CNT100    ;
   265:L P[265] 100mm/sec CNT100    ;
   266:L P[266] 100mm/sec CNT100    ;
   267:L P[267] 100mm/sec CNT100    ;
   268:L P[268] 100mm/sec CNT100    ;
   269:L P[269] 100mm/sec CNT100    ;
   270:L P[270] 100mm/sec CNT100    ;
   271:L P[271] 100mm/sec CNT100    ;
   272:L P[272] 100mm/sec CNT100    ;
   273:L P[273] 100mm/sec CNT100    ;
   274:L P[274] 100mm/sec CNT100    ;
   275:L P[275] 100mm/sec CNT100    ;
   276:L P[276] 100mm/sec CNT100    ;
   277:L P[277] 100mm/sec CNT100    ;
   278:L P[278] 100mm/sec CNT100    ;
   279:L P[279] 100mm/sec CNT100    ;
   280:L P[280] 100mm/sec CNT100    ;
   281:L P[281] 100mm/sec CNT100    ;
   282:L P[282] 100mm/sec CNT100    ;
   283:L P[283] 100mm/sec CNT100    ;
   284:L P[284] 100mm/sec CNT100    ;
   285:L P[285] 100mm/sec CNT100    ;
   286:L P[286] 100mm/sec CNT100    ;
   287:L P[287] 100mm/sec CNT100    ;
   288:L P[288] 100mm/sec CNT100    ;
   289:L P[289] 100mm/sec CNT100    ;
   290:L P[290] 100mm/sec CNT100    ;
   291:L P[291] 100mm/sec CNT100    ;
   292:L P[292] 100mm/sec CNT100    ;
   293:L P[293] 100mm/sec CNT100    ;
   294:L P[294] 100mm/sec CNT100    ;
   295:L P[295] 100mm/sec CNT100    ;
   296:L P[296] 100mm/sec CNT100    ;
   297:L P[297] 100mm/sec CNT100    ;
   298:L P[298] 100mm/sec CNT100    ;
   299:L P[299] 100mm/sec CNT100    ;
   300:L P[300] 100mm/sec CNT100    ;
   301:L P[301] 100mm/sec CNT100    ;
   302:L P[302] 100mm/sec CNT100    ;
   303:L P[303] 100mm/sec CNT100    ;
   304:L P[304] 100mm/sec CNT100    ;
   305:L P[305] 100mm/sec CNT100    ;
   306:L P[306] 100mm/sec CNT100    ;
   307:L P[307] 100mm/sec CNT100    ;
   308:L P[308] 100mm/sec CNT100    ;
   309:L P[309] 100mm/sec CNT100    ;
   310:L P[310] 100mm/sec CNT100    ;
   311:L P[311] 100mm/sec CNT100    ;
   312:L P[312] 100mm/sec CNT100    ;
   313:L P[313] 100mm/sec CNT100    ;
   314:L P[314] 100mm/sec CNT100    ;
   315:L P[315] 100mm/sec CNT100    ;
   316:L P[316] 100mm/sec CNT100    ;
   317:L P[317] 100mm/sec CNT100    ;
   318:L P[318] 100mm/sec CNT100    ;
   319:L P[319] 100mm/sec CNT100    ;
   320:L P[320] 100mm/sec CNT100    ;
   321:L P[321] 100mm/sec CNT100    ;
   322:L P[322] 100mm/sec CNT100    ;
   323:L P[323] 100mm/sec CNT100    ;
   324:L P[324] 100mm/sec CNT100    ;
   325:L P[325] 100mm/sec CNT100    ;
   326:L P[326] 100mm/sec CNT100    ;
   327:L P[327] 100mm/sec CNT100    ;
   328:L P[328] 100mm/sec CNT100    ;
   329:L P[329] 100mm/sec CNT100    ;
   330:L P[330] 100mm/sec CNT100    ;
   331:L P[331] 100mm/sec CNT100    ;
   332:L P[332] 100mm/sec CNT100    ;
   333:L P[333] 100mm/sec CNT100    ;
   334:L P[334] 100mm/sec CNT100    ;
   335:L P[335] 100mm/sec CNT100    ;
   336:L P[336] 100mm/sec CNT100    ;
   337:L P[337] 100mm/sec CNT100    ;
   338:L P[338] 100mm/sec CNT100    ;
   339:L P[339] 100mm/sec CNT100    ;
   340:L P[340] 100mm/sec CNT100    ;
   341:L P[341] 100mm/sec CNT100    ;
   342:L P[342] 100mm/sec CNT100    ;
   343:L P[343] 100mm/sec CNT100    ;
   344:L P[344] 100mm/sec CNT100    ;
   345:L P[345] 100mm/sec CNT100    ;
   346:L P[346] 100mm/sec CNT100    ;
   347:L P[347] 100mm/sec CNT100    ;
   348:L P[348] 100mm/sec CNT100    ;
   349:L P[349] 100mm/sec CNT100    ;
   350:L P[350] 100mm/sec CNT100    ;
   351:L P[351] 100mm/sec CNT100    ;
   352:L P[352] 100mm/sec CNT100    ;
   353:L P[353] 100mm/sec CNT100    ;
   354:L P[354] 100mm/sec CNT100    ;
   355:L P[355] 100mm/sec CNT100    ;
   356:L P[356] 100mm/sec CNT100    ;
   357:L P[357] 100mm/sec CNT100    ;
   358:L P[358] 100mm/sec CNT100    ;
   359:L P[359] 100mm/sec CNT100    ;
   360:L P[360] 100mm/sec CNT100    ;
   361:L P[361] 100mm/sec CNT100    ;
   362:L P[362] 100mm/sec CNT100    ;
   363:L P[363] 100mm/sec CNT100    ;
   364:L P[364] 100mm/sec CNT100    ;
   365:L P[365] 100mm/sec CNT100    ;
   366:L P[366] 100mm/sec CNT100    ;
   367:L P[367] 100mm/sec CNT100    ;
   368:L P[368] 100mm/sec CNT100    ;
   369:L P[369] 100mm/sec CNT100    ;
   370:L P[370] 100mm/sec CNT100    ;
   371:L P[371] 100mm/sec CNT100    ;
   372:L P[372] 100mm/sec CNT100    ;
   373:L P[373] 100mm/sec CNT100    ;
   374:L P[374] 100mm/sec CNT100    ;
   375:L P[375] 100mm/sec CNT100    ;
   376:L P[376] 100mm/sec CNT100    ;
   377:L P[377] 100mm/sec CNT100    ;
   378:L P[378] 100mm/sec CNT100    ;
   379:L P[379] 100mm/sec CNT100    ;
   380:L P[380] 100mm/sec CNT100    ;
   381:L P[381] 100mm/sec CNT100    ;
   382:L P[382] 100mm/sec CNT100    ;
   383:L P[383] 100mm/sec CNT100    ;
   384:L P[384] 100mm/sec CNT100    ;
   385:L P[385] 100mm/sec CNT100    ;
   386:L P[386] 100mm/sec CNT100    ;
   387:L P[387] 100mm/sec CNT100    ;
   388:L P[388] 100mm/sec CNT100    ;
   389:L P[389] 100mm/sec CNT100    ;
   390:L P[390] 100mm/sec CNT100    ;
   391:L P[391] 100mm/sec CNT100    ;
   392:L P[392] 100mm/sec CNT100    ;
   393:L P[393] 100mm/sec CNT100    ;
   394:L P[394] 100mm/sec CNT100    ;
   395:L P[395] 100mm/sec CNT100    ;
   396:L P[396] 100mm/sec CNT100    ;
   397:L P[397] 100mm/sec CNT100    ;
   398:L P[398] 100mm/sec CNT100    ;
   399:L P[399] 100mm/sec CNT100    ;
   400:L P[400] 100mm/sec CNT100    ;
   401:L P[401] 100mm/sec CNT100    ;
   402:L P[402] 100mm/sec CNT100    ;
   403:L P[403] 100mm/sec CNT100    ;
   404:L P[404] 100mm/sec CNT100    ;
   405:L P[405] 100mm/sec CNT100    ;
   406:L P[406] 100mm/sec CNT100    ;
   407:L P[407] 100mm/sec CNT100    ;
   408:L P[408] 100mm/sec CNT100    ;
   409:L P[409] 100mm/sec CNT100    ;
   410:L P[410] 100mm/sec CNT100    ;
   411:L P[411] 100mm/sec CNT100    ;
   412:L P[412] 100mm/sec CNT100    ;
   413:L P[413] 100mm/sec CNT100    ;
   414:L P[414] 100mm/sec CNT100    ;
   415:L P[415] 100mm/sec CNT100    ;
   416:L P[416] 100mm/sec CNT100    ;
   417:L P[417] 100mm/sec CNT100    ;
   418:L P[418] 100mm/sec CNT100    ;
   419:L P[419] 100mm/sec CNT100    ;
   420:L P[420] 100mm/sec CNT100    ;
   421:L P[421] 100mm/sec CNT100    ;
   422:L P[422] 100mm/sec CNT100    ;
   423:L P[423] 100mm/sec CNT100    ;
   424:L P[424] 100mm/sec CNT100    ;
   425:L P[425] 100mm/sec CNT100    ;
   426:L P[426] 100mm/sec CNT100    ;
   427:L P[427] 100mm/sec CNT100    ;
   428:L P[428] 100mm/sec CNT100    ;
   429:L P[429] 100mm/sec CNT100    ;
   430:L P[430] 100mm/sec CNT100    ;
   431:L P[431] 100mm/sec CNT100    ;
   432:L P[432] 100mm/sec CNT100    ;
   433:L P[433] 100mm/sec CNT100    ;
   434:L P[434] 100mm/sec CNT100    ;
   435:L P[435] 100mm/sec CNT100    ;
   436:L P[436] 100mm/sec CNT100    ;
   437:L P[437] 100mm/sec CNT100    ;
   438:L P[438] 100mm/sec CNT100    ;
   439:L P[439] 100mm/sec CNT100    ;
   440:L P[440] 100mm/sec CNT100    ;
   441:L P[441] 100mm/sec CNT100    ;
   442:L P[442] 100mm/sec CNT100    ;
   443:L P[443] 100mm/sec CNT100    ;
   444:L P[444] 100mm/sec CNT100    ;
   445:L P[445] 100mm/sec CNT100    ;
   446:L P[446] 100mm/sec CNT100    ;
   447:L P[447] 100mm/sec CNT100    ;
   448:L P[448] 100mm/sec CNT100    ;
   449:L P[449] 100mm/sec CNT100    ;
   450:L P[450] 100mm/sec CNT100    ;
   451:L P[451] 100mm/sec CNT100    ;
   452:L P[452] 100mm/sec CNT100    ;
   453:L P[453] 100mm/sec CNT100    ;
   454:L P[454] 100mm/sec CNT100    ;
   455:L P[455] 100mm/sec CNT100    ;
   456:L P[456] 100mm/sec CNT100    ;
   457:L P[457] 100mm/sec CNT100    ;
   458:L P[458] 100mm/sec CNT100    ;
   459:L P[459] 100mm/sec CNT100    ;
   460:L P[460] 100mm/sec CNT100    ;
   461:L P[461] 100mm/sec CNT100    ;
   462:L P[462] 100mm/sec CNT100    ;
   463:L P[463] 100mm/sec CNT100    ;
   464:L P[464] 100mm/sec CNT100    ;
   465:L P[465] 100mm/sec CNT100    ;
   466:L P[466] 100mm/sec CNT100    ;
   467:L P[467] 100mm/sec CNT100    ;
   468:L P[468] 100mm/sec CNT100    ;
   469:L P[469] 100mm/sec CNT100    ;
   470:L P[470] 100mm/sec CNT100    ;
   471:L P[471] 100mm/sec CNT100    ;
   472:L P[472] 100mm/sec CNT100    ;
   473:L P[473] 100mm/sec CNT100    ;
   474:L P[474] 100mm/sec CNT100    ;
   475:L P[475] 100mm/sec CNT100    ;
   476:L P[476] 100mm/sec CNT100    ;
   477:L P[477] 100mm/sec CNT100    ;
   478:L P[478] 100mm/sec CNT100    ;
   479:L P[479] 100mm/sec CNT100    ;
   480:L P[480] 100mm/sec CNT100    ;
   481:L P[481] 100mm/sec CNT100    ;
   482:L P[482] 100mm/sec CNT100    ;
   483:L P[483] 100mm/sec CNT100    ;
   484:L P[484] 100mm/sec CNT100    ;
   485:L P[485] 100mm/sec CNT100    ;
   486:L P[486] 100mm/sec CNT100    ;
   487:L P[487] 100mm/sec CNT100    ;
   488:L P[488] 100mm/sec CNT100    ;
   489:L P[489] 100mm/sec CNT100    ;
   490:L P[490] 100mm/sec CNT100    ;
   491:L P[491] 100mm/sec CNT100    ;
   492:L P[492] 100mm/sec CNT100    ;
   493:L P[493] 100mm/sec CNT100    ;
   494:L P[494] 100mm/sec CNT100    ;
   495:L P[495] 100mm/sec CNT100    ;
   496:L P[496] 100mm/sec CNT100    ;
   497:L P[497] 100mm/sec CNT100    ;
   498:L P[498] 100mm/sec CNT100    ;
   499:L P[499] 100mm/sec CNT100    ;
   500:L P[500] 100mm/sec CNT100    ;
   501:L P[501] 100mm/sec CNT100    ;
   502:L P[502] 100mm/sec CNT100    ;
   503:L P[503] 100mm/sec CNT100    ;
   504:L P[504] 100mm/sec CNT100    ;
   505:L P[505] 100mm/sec CNT100    ;
   506:L P[506] 100mm/sec CNT100    ;
   507:L P[507] 100mm/sec CNT100    ;
   508:L P[508] 100mm/sec CNT100    ;
   509:L P[509] 100mm/sec CNT100    ;
   510:L P[510] 100mm/sec CNT100    ;
   511:L P[511] 100mm/sec CNT100    ;
   512:L P[512] 100mm/sec CNT100    ;
   513:L P[513] 100mm/sec CNT100    ;
   514:L P[514] 100mm/sec CNT100    ;
   515:L P[515] 100mm/sec CNT100    ;
   516:L P[516] 100mm/sec CNT100    ;
   517:L P[517] 100mm/sec CNT100    ;
   518:L P[518] 100mm/sec CNT100    ;
   519:L P[519] 100mm/sec CNT100    ;
   520:L P[520] 100mm/sec CNT100    ;
   521:L P[521] 100mm/sec CNT100    ;
   522:L P[522] 100mm/sec CNT100    ;
   523:L P[523] 100mm/sec CNT100    ;
   524:L P[524] 100mm/sec CNT100    ;
   525:L P[525] 100mm/sec CNT100    ;
   526:L P[526] 100mm/sec CNT100    ;
   527:L P[527] 100mm/sec CNT100    ;
   528:L P[528] 100mm/sec CNT100    ;
   529:L P[529] 100mm/sec CNT100    ;
   530:L P[530] 100mm/sec CNT100    ;
   531:L P[531] 100mm/sec CNT100    ;
   532:L P[532] 100mm/sec CNT100    ;
   533:L P[533] 100mm/sec CNT100    ;
   534:L P[534] 100mm/sec CNT100    ;
   535:L P[535] 100mm/sec CNT100    ;
   536:L P[536] 100mm/sec CNT100    ;
   537:L P[537] 100mm/sec CNT100    ;
   538:L P[538] 100mm/sec CNT100    ;
   539:L P[539] 100mm/sec CNT100    ;
   540:L P[540] 100mm/sec CNT100    ;
   541:L P[541] 100mm/sec CNT100    ;
   542:L P[542] 100mm/sec CNT100    ;
   543:L P[543] 100mm/sec CNT100    ;
   544:L P[544] 100mm/sec CNT100    ;
   545:L P[545] 100mm/sec CNT100    ;
   546:L P[546] 100mm/sec CNT100    ;
   547:L P[547] 100mm/sec CNT100    ;
   548:L P[548] 100mm/sec CNT100    ;
   549:L P[549] 100mm/sec CNT100    ;
   550:L P[550] 100mm/sec CNT100    ;
   551:L P[551] 100mm/sec CNT100    ;
   552:L P[552] 100mm/sec CNT100    ;
   553:L P[553] 100mm/sec CNT100    ;
   554:L P[554] 100mm/sec CNT100    ;
   555:L P[555] 100mm/sec CNT100    ;
   556:L P[556] 100mm/sec CNT100    ;
   557:L P[557] 100mm/sec CNT100    ;
   558:L P[558] 100mm/sec CNT100    ;
   559:L P[559] 100mm/sec CNT100    ;
   560:L P[560] 100mm/sec CNT100    ;
   561:L P[561] 100mm/sec CNT100    ;
   562:L P[562] 100mm/sec CNT100    ;
   563:L P[563] 100mm/sec CNT100    ;
   564:L P[564] 100mm/sec CNT100    ;
   565:L P[565] 100mm/sec CNT100    ;
   566:L P[566] 100mm/sec CNT100    ;
   567:L P[567] 100mm/sec CNT100    ;
   568:L P[568] 100mm/sec CNT100    ;
   569:L P[569] 100mm/sec CNT100    ;
   570:L P[570] 100mm/sec CNT100    ;
   571:L P[571] 100mm/sec CNT100    ;
   572:L P[572] 100mm/sec CNT100    ;
   573:L P[573] 100mm/sec CNT100    ;
   574:L P[574] 100mm/sec CNT100    ;
   575:L P[575] 100mm/sec CNT100    ;
   576:L P[576] 100mm/sec CNT100    ;
   577:L P[577] 100mm/sec CNT100    ;
   578:L P[578] 100mm/sec CNT100    ;
   579:L P[579] 100mm/sec CNT100    ;
   580:L P[580] 100mm/sec CNT100    ;
   581:L P[581] 100mm/sec CNT100    ;
   582:L P[582] 100mm/sec CNT100    ;
   583:L P[583] 100mm/sec CNT100    ;
   584:L P[584] 100mm/sec CNT100    ;
   585:L P[585] 100mm/sec CNT100    ;
   586:L P[586] 100mm/sec CNT100    ;
   587:L P[587] 100mm/sec CNT100    ;
   588:L P[588] 100mm/sec CNT100    ;
   589:L P[589] 100mm/sec CNT100    ;
   590:L P[590] 100mm/sec CNT100    ;
   591:L P[591] 100mm/sec CNT100    ;
   592:L P[592] 100mm/sec CNT100    ;
   593:L P[593] 100mm/sec CNT100    ;
   594:L P[594] 100mm/sec CNT100    ;
   595:L P[595] 100mm/sec CNT100    ;
   596:L P[596] 100mm/sec CNT100    ;
   597:L P[597] 100mm/sec CNT100    ;
   598:L P[598] 100mm/sec CNT100    ;
   599:L P[599] 100mm/sec CNT100    ;
   600:L P[600] 100mm/sec CNT100    ;
   601:L P[601] 100mm/sec CNT100    ;
   602:L P[602] 100mm/sec CNT100    ;
   603:L P[603] 100mm/sec CNT100    ;
   604:L P[604] 100mm/sec CNT100    ;
   605:L P[605] 100mm/sec CNT100    ;
   606:L P[606] 100mm/sec CNT100    ;
   607:L P[607] 100mm/sec CNT100    ;
   608:L P[608] 100mm/sec CNT100    ;
   609:L P[609] 100mm/sec CNT100    ;
   610:L P[610] 100mm/sec CNT100    ;
   611:L P[611] 100mm/sec CNT100    ;
   612:L P[612] 100mm/sec CNT100    ;
   613:L P[613] 100mm/sec CNT100    ;
   614:L P[614] 100mm/sec CNT100    ;
   615:L P[615] 100mm/sec CNT100    ;
   616:L P[616] 100mm/sec CNT100    ;
   617:L P[617] 100mm/sec CNT100    ;
   618:L P[618] 100mm/sec CNT100    ;
   619:L P[619] 100mm/sec CNT100    ;
   620:L P[620] 100mm/sec CNT100    ;
   621:L P[621] 100mm/sec CNT100    ;
   622:L P[622] 100mm/sec CNT100    ;
   623:L P[623] 100mm/sec CNT100    ;
   624:L P[624] 100mm/sec CNT100    ;
   625:L P[625] 100mm/sec CNT100    ;
   626:L P[626] 100mm/sec CNT100    ;
   627:L P[627] 100mm/sec CNT100    ;
   628:L P[628] 100mm/sec CNT100    ;
   629:L P[629] 100mm/sec CNT100    ;
   630:L P[630] 100mm/sec CNT100    ;
   631:L P[631] 100mm/sec CNT100    ;
   632:L P[632] 100mm/sec CNT100    ;
   633:L P[633] 100mm/sec CNT100    ;
   634:L P[634] 100mm/sec CNT100    ;
   635:L P[635] 100mm/sec CNT100    ;
   636:L P[636] 100mm/sec CNT100    ;
   637:L P[637] 100mm/sec CNT100    ;
   638:L P[638] 100mm/sec CNT100    ;
/POS
P[1]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  420.246  mm,    Y =   0.000  mm,    Z =   53.417  mm,
    W =  -180.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[2]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  460.744  mm,    Y =   -216.786  mm,    Z =   -216.340  mm,
    W =  -180.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[3]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   -23.511  mm,    Z =   -206.340  mm,
    W =  -170.024 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[4]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   -18.331  mm,    Z =   -205.570  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[5]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   -15.836  mm,    Z =   -205.416  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[6]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   -12.645  mm,    Z =   -204.035  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[7]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   -9.398  mm,    Z =   -202.655  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[8]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   -6.609  mm,    Z =   -201.965  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[9]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   -4.757  mm,    Z =   -201.965  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[10]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   -4.757  mm,    Z =   -201.965  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[11]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   -3.336  mm,    Z =   -200.750  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[12]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   -0.544  mm,    Z =   -200.448  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[13]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   2.680  mm,    Z =   -199.543  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[14]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   4.515  mm,    Z =   -199.543  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[15]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   5.891  mm,    Z =   -197.879  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[16]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   8.184  mm,    Z =   -197.879  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[17]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   11.394  mm,    Z =   -197.396  mm,
    W =  -171.070 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[18]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   14.601  mm,    Z =   -196.874  mm,
    W =  -170.294 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[19]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   17.329  mm,    Z =   -196.151  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[20]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   19.584  mm,    Z =   -196.151  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[21]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   21.389  mm,    Z =   -193.871  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[22]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   23.626  mm,    Z =   -193.871  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[23]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   25.399  mm,    Z =   -193.871  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[24]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   26.752  mm,    Z =   -191.980  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[25]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   29.454  mm,    Z =   -191.691  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[26]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   32.557  mm,    Z =   -190.824  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[27]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   34.742  mm,    Z =   -190.824  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[28]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   36.536  mm,    Z =   -189.709  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[29]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   38.715  mm,    Z =   -189.709  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[30]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   41.433  mm,    Z =   -189.177  mm,
    W =  -171.163 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[31]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   44.553  mm,    Z =   -188.884  mm,
    W =  -170.623 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[32]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   47.575  mm,    Z =   -188.005  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[33]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   49.662  mm,    Z =   -188.005  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[34]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   51.443  mm,    Z =   -185.965  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[35]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   53.506  mm,    Z =   -185.965  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[36]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   56.456  mm,    Z =   -184.565  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[37]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   59.341  mm,    Z =   -184.098  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[38]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   60.957  mm,    Z =   -182.796  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[39]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   62.709  mm,    Z =   -182.796  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[40]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   65.337  mm,    Z =   -182.609  mm,
    W =  -171.668 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[41]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   68.471  mm,    Z =   -182.234  mm,
    W =  -173.605 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[42]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   71.525  mm,    Z =   -181.654  mm,
    W =  -171.283 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[43]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   74.096  mm,    Z =   -181.654  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[44]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   75.848  mm,    Z =   -180.706  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[45]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   77.493  mm,    Z =   -180.706  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[46]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   80.255  mm,    Z =   -180.189  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[47]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   83.696  mm,    Z =   -179.568  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[48]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   86.578  mm,    Z =   -178.749  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[49]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   89.006  mm,    Z =   -178.749  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[50]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   90.687  mm,    Z =   -177.794  mm,
    W =  -170.305 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[51]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   92.418  mm,    Z =   -177.794  mm,
    W =  -171.536 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[52]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   95.510  mm,    Z =   -177.463  mm,
    W =  -173.981 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[53]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   98.733  mm,    Z =   -177.132  mm,
    W =  -175.235 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[54]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   101.337  mm,    Z =   -176.925  mm,
    W =  -176.049 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[55]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   104.376  mm,    Z =   -176.830  mm,
    W =  -175.827 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[56]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   107.652  mm,    Z =   -176.546  mm,
    W =  -175.070 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[57]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   110.539  mm,    Z =   -176.180  mm,
    W =  -175.137 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[58]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   113.545  mm,    Z =   -175.936  mm,
    W =  -176.709 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[59]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   116.488  mm,    Z =   -175.839  mm,
    W =  -179.610 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[60]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   119.481  mm,    Z =   -175.896  mm,
    W =  -181.094 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[61]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   122.493  mm,    Z =   -176.140  mm,
    W =  -181.173 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[62]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  461.433  mm,    Y =   125.801  mm,    Z =   -176.044  mm,
    W =  -180.398 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[63]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  460.744  mm,    Y =   209.140  mm,    Z =   -186.044  mm,
    W =  -180.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[64]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  477.842  mm,    Y =   209.140  mm,    Z =   -186.044  mm,
    W =  -180.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[65]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   125.801  mm,    Z =   -176.044  mm,
    W =  -180.398 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[66]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   122.493  mm,    Z =   -176.140  mm,
    W =  -181.173 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[67]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   119.481  mm,    Z =   -175.896  mm,
    W =  -181.094 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[68]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   116.488  mm,    Z =   -175.839  mm,
    W =  -179.610 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[69]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   113.545  mm,    Z =   -175.936  mm,
    W =  -176.709 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[70]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   110.539  mm,    Z =   -176.180  mm,
    W =  -175.137 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[71]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   107.652  mm,    Z =   -176.546  mm,
    W =  -175.070 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[72]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   104.376  mm,    Z =   -176.830  mm,
    W =  -175.827 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[73]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   101.337  mm,    Z =   -176.925  mm,
    W =  -176.049 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[74]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   98.733  mm,    Z =   -177.132  mm,
    W =  -175.235 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[75]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   95.510  mm,    Z =   -177.463  mm,
    W =  -173.981 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[76]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   92.418  mm,    Z =   -177.794  mm,
    W =  -171.536 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[77]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   90.687  mm,    Z =   -177.794  mm,
    W =  -170.305 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[78]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   89.006  mm,    Z =   -178.749  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[79]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   86.578  mm,    Z =   -178.749  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[80]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   83.696  mm,    Z =   -179.568  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[81]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   80.255  mm,    Z =   -180.189  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[82]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   77.493  mm,    Z =   -180.706  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[83]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   75.848  mm,    Z =   -180.706  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[84]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   74.096  mm,    Z =   -181.654  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[85]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   71.525  mm,    Z =   -181.654  mm,
    W =  -171.283 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[86]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   68.471  mm,    Z =   -182.234  mm,
    W =  -173.605 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[87]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   65.337  mm,    Z =   -182.609  mm,
    W =  -171.668 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[88]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   62.709  mm,    Z =   -182.796  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[89]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   60.957  mm,    Z =   -182.796  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[90]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   59.341  mm,    Z =   -184.098  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[91]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   56.456  mm,    Z =   -184.565  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[92]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   53.506  mm,    Z =   -185.965  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[93]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   51.443  mm,    Z =   -185.965  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[94]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   49.662  mm,    Z =   -188.005  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[95]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   47.575  mm,    Z =   -188.005  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[96]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   44.553  mm,    Z =   -188.884  mm,
    W =  -170.623 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[97]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   41.433  mm,    Z =   -189.177  mm,
    W =  -171.163 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[98]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   38.715  mm,    Z =   -189.709  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[99]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   36.536  mm,    Z =   -189.709  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[100]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   34.742  mm,    Z =   -190.824  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[101]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   32.557  mm,    Z =   -190.824  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[102]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   29.454  mm,    Z =   -191.691  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[103]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   26.752  mm,    Z =   -191.980  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[104]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   25.399  mm,    Z =   -193.871  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[105]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   23.626  mm,    Z =   -193.871  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[106]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   21.389  mm,    Z =   -193.871  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[107]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   19.584  mm,    Z =   -196.151  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[108]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   17.329  mm,    Z =   -196.151  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[109]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   14.601  mm,    Z =   -196.874  mm,
    W =  -170.294 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[110]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   11.394  mm,    Z =   -197.396  mm,
    W =  -171.070 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[111]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   8.184  mm,    Z =   -197.879  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[112]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   5.891  mm,    Z =   -197.879  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[113]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   4.515  mm,    Z =   -199.543  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[114]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   2.680  mm,    Z =   -199.543  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[115]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   -0.544  mm,    Z =   -200.448  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[116]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   -3.336  mm,    Z =   -200.750  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[117]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   -4.757  mm,    Z =   -201.965  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[118]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   -4.757  mm,    Z =   -201.965  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[119]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   -6.609  mm,    Z =   -201.965  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[120]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   -9.398  mm,    Z =   -202.655  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[121]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   -12.645  mm,    Z =   -204.035  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[122]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   -15.836  mm,    Z =   -205.416  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[123]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   -18.331  mm,    Z =   -205.570  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[124]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  478.531  mm,    Y =   -23.511  mm,    Z =   -206.340  mm,
    W =  -170.024 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[125]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  477.842  mm,    Y =   -216.786  mm,    Z =   -216.340  mm,
    W =  -180.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[126]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  494.940  mm,    Y =   -216.786  mm,    Z =   -244.748  mm,
    W =  -180.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[127]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -137.787  mm,    Z =   -234.748  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[128]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -135.386  mm,    Z =   -234.145  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[129]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -132.555  mm,    Z =   -232.939  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[130]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -130.299  mm,    Z =   -232.939  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[131]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -128.610  mm,    Z =   -231.808  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[132]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -126.531  mm,    Z =   -231.808  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[133]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -123.766  mm,    Z =   -231.372  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[134]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -120.552  mm,    Z =   -230.725  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[135]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -117.455  mm,    Z =   -229.723  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[136]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -115.244  mm,    Z =   -229.723  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[137]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -113.920  mm,    Z =   -227.833  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[138]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -109.980  mm,    Z =   -227.833  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[139]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -108.348  mm,    Z =   -225.397  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[140]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -105.253  mm,    Z =   -224.703  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[141]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -102.422  mm,    Z =   -223.313  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[142]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -100.327  mm,    Z =   -223.313  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[143]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -98.772  mm,    Z =   -222.084  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[144]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -96.735  mm,    Z =   -222.084  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[145]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -93.607  mm,    Z =   -221.112  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[146]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -90.644  mm,    Z =   -220.835  mm,
    W =  -171.933 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[147]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -87.566  mm,    Z =   -220.449  mm,
    W =  -173.619 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[148]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -85.548  mm,    Z =   -220.449  mm,
    W =  -172.556 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[149]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -84.102  mm,    Z =   -219.768  mm,
    W =  -170.965 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[150]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -81.495  mm,    Z =   -219.768  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[151]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   -78.474  mm,    Z =   -218.854  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[152]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   60.498  mm,    Z =   -182.796  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[153]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  495.909  mm,    Y =   145.696  mm,    Z =   -176.478  mm,
    W =  -182.720 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[154]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  494.940  mm,    Y =   209.140  mm,    Z =   -186.478  mm,
    W =  -180.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[155]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  512.038  mm,    Y =   209.140  mm,    Z =   -186.520  mm,
    W =  -180.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[156]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   146.636  mm,    Z =   -176.520  mm,
    W =  -181.456 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[157]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   143.272  mm,    Z =   -176.709  mm,
    W =  -182.158 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[158]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   140.257  mm,    Z =   -176.383  mm,
    W =  -183.357 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[159]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   137.547  mm,    Z =   -176.220  mm,
    W =  -183.952 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[160]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   134.566  mm,    Z =   -176.025  mm,
    W =  -182.367 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[161]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   131.449  mm,    Z =   -175.965  mm,
    W =  -180.451 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[162]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   128.428  mm,    Z =   -175.981  mm,
    W =  -179.379 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[163]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   125.407  mm,    Z =   -176.060  mm,
    W =  -179.828 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[164]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   122.387  mm,    Z =   -176.140  mm,
    W =  -180.855 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[165]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   119.366  mm,    Z =   -175.905  mm,
    W =  -181.243 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[166]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   116.346  mm,    Z =   -175.827  mm,
    W =  -179.469 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[167]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   113.550  mm,    Z =   -175.936  mm,
    W =  -176.770 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[168]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   110.333  mm,    Z =   -176.213  mm,
    W =  -174.632 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[169]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   107.335  mm,    Z =   -176.546  mm,
    W =  -174.684 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[170]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   104.537  mm,    Z =   -176.925  mm,
    W =  -175.862 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[171]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   101.507  mm,    Z =   -176.977  mm,
    W =  -176.158 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[172]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   98.647  mm,    Z =   -177.132  mm,
    W =  -175.523 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[173]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   95.755  mm,    Z =   -177.463  mm,
    W =  -173.993 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[174]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   92.457  mm,    Z =   -177.794  mm,
    W =  -170.807 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[175]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   89.441  mm,    Z =   -178.749  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[176]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   86.495  mm,    Z =   -178.938  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[177]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   83.627  mm,    Z =   -179.568  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[178]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   80.603  mm,    Z =   -180.137  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[179]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   77.600  mm,    Z =   -180.706  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[180]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   75.848  mm,    Z =   -180.706  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[181]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   74.126  mm,    Z =   -181.654  mm,
    W =  -170.041 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[182]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   71.555  mm,    Z =   -181.654  mm,
    W =  -171.697 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[183]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   68.484  mm,    Z =   -182.234  mm,
    W =  -173.734 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[184]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   65.414  mm,    Z =   -182.515  mm,
    W =  -171.120 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[185]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   62.370  mm,    Z =   -182.796  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[186]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   59.431  mm,    Z =   -184.098  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[187]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   56.584  mm,    Z =   -184.565  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[188]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   53.277  mm,    Z =   -185.965  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[189]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   51.109  mm,    Z =   -185.965  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[190]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   49.878  mm,    Z =   -188.005  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[191]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   47.573  mm,    Z =   -188.005  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[192]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   44.556  mm,    Z =   -188.964  mm,
    W =  -170.837 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[193]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   41.549  mm,    Z =   -189.177  mm,
    W =  -170.944 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[194]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   38.407  mm,    Z =   -189.709  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[195]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   36.198  mm,    Z =   -189.709  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[196]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   34.868  mm,    Z =   -190.824  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[197]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   32.625  mm,    Z =   -190.824  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[198]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   29.496  mm,    Z =   -191.691  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[199]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   26.356  mm,    Z =   -191.980  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[200]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   23.666  mm,    Z =   -193.871  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[201]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   21.424  mm,    Z =   -193.871  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[202]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   19.618  mm,    Z =   -196.151  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[203]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   17.653  mm,    Z =   -196.151  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[204]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -0.693  mm,    Z =   -200.750  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[205]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -3.046  mm,    Z =   -200.750  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[206]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -4.907  mm,    Z =   -201.965  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[207]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -6.837  mm,    Z =   -201.965  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[208]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -9.747  mm,    Z =   -203.345  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[209]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -12.543  mm,    Z =   -204.035  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[210]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -15.667  mm,    Z =   -205.416  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[211]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -18.445  mm,    Z =   -205.416  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[212]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -21.334  mm,    Z =   -206.340  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[213]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -24.221  mm,    Z =   -206.719  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[214]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -27.400  mm,    Z =   -207.476  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[215]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -29.076  mm,    Z =   -207.476  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[216]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -30.859  mm,    Z =   -208.329  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[217]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -33.703  mm,    Z =   -208.668  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[218]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -36.624  mm,    Z =   -209.855  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[219]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -38.858  mm,    Z =   -209.855  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[220]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -40.280  mm,    Z =   -211.710  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[221]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -42.690  mm,    Z =   -211.710  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[222]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -45.663  mm,    Z =   -213.124  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[223]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -48.536  mm,    Z =   -213.124  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[224]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -51.410  mm,    Z =   -213.989  mm,
    W =  -170.159 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[225]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -54.283  mm,    Z =   -214.292  mm,
    W =  -170.041 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[226]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -57.219  mm,    Z =   -214.898  mm,
    W =  -170.881 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[227]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -60.117  mm,    Z =   -215.413  mm,
    W =  -171.301 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[228]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -63.224  mm,    Z =   -215.722  mm,
    W =  -173.449 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[229]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -66.593  mm,    Z =   -216.192  mm,
    W =  -170.624 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[230]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -68.870  mm,    Z =   -216.192  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[231]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -70.348  mm,    Z =   -217.304  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[232]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -72.839  mm,    Z =   -217.304  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[233]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -75.760  mm,    Z =   -218.854  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[234]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -78.287  mm,    Z =   -218.854  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[235]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -81.064  mm,    Z =   -219.768  mm,
    W =  -170.686 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[236]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -83.654  mm,    Z =   -219.768  mm,
    W =  -170.074 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[237]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -85.107  mm,    Z =   -220.449  mm,
    W =  -173.081 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[238]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -87.292  mm,    Z =   -220.449  mm,
    W =  -174.311 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[239]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -90.279  mm,    Z =   -220.738  mm,
    W =  -172.753 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[240]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -93.141  mm,    Z =   -220.835  mm,
    W =  -170.678 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[241]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -96.282  mm,    Z =   -222.084  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[242]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -98.781  mm,    Z =   -222.084  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[243]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -100.442  mm,    Z =   -223.313  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[244]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -102.599  mm,    Z =   -223.313  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[245]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -105.354  mm,    Z =   -225.397  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[246]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -107.918  mm,    Z =   -225.397  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[247]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -109.640  mm,    Z =   -227.833  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[248]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -111.612  mm,    Z =   -227.833  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[249]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -113.854  mm,    Z =   -227.833  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[250]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -115.355  mm,    Z =   -229.723  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[251]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -117.681  mm,    Z =   -229.723  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[252]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -120.774  mm,    Z =   -231.226  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[253]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -123.531  mm,    Z =   -231.226  mm,
    W =  -170.512 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[254]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -126.245  mm,    Z =   -231.808  mm,
    W =  -170.245 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[255]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -128.622  mm,    Z =   -231.808  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[256]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -130.245  mm,    Z =   -232.939  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[257]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -132.245  mm,    Z =   -232.939  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[258]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -135.586  mm,    Z =   -234.547  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[259]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -138.459  mm,    Z =   -234.748  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[260]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -141.477  mm,    Z =   -236.150  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[261]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -144.489  mm,    Z =   -236.714  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[262]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -147.055  mm,    Z =   -237.277  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[263]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -149.125  mm,    Z =   -237.277  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[264]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -151.068  mm,    Z =   -238.794  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[265]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -153.740  mm,    Z =   -239.062  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[266]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  511.450  mm,    Y =   -156.125  mm,    Z =   -240.402  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[267]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  512.038  mm,    Y =   -216.786  mm,    Z =   -250.402  mm,
    W =  -180.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[268]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.137  mm,    Y =   -216.786  mm,    Z =   -250.402  mm,
    W =  -180.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[269]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -156.711  mm,    Z =   -240.402  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[270]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -153.984  mm,    Z =   -239.397  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[271]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -150.769  mm,    Z =   -238.794  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[272]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -147.766  mm,    Z =   -237.277  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[273]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -144.505  mm,    Z =   -236.714  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[274]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -141.607  mm,    Z =   -236.150  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[275]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -139.962  mm,    Z =   -236.150  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[276]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -138.371  mm,    Z =   -234.748  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[277]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -135.471  mm,    Z =   -234.145  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[278]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -132.385  mm,    Z =   -232.939  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[279]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -130.109  mm,    Z =   -232.939  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[280]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -128.574  mm,    Z =   -231.808  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[281]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -126.476  mm,    Z =   -231.808  mm,
    W =  -170.905 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[282]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -123.332  mm,    Z =   -231.226  mm,
    W =  -170.290 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[283]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -120.603  mm,    Z =   -231.038  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[284]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -117.751  mm,    Z =   -229.723  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[285]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -115.687  mm,    Z =   -229.723  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[286]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -114.073  mm,    Z =   -227.833  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[287]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -111.452  mm,    Z =   -227.833  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[288]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -109.927  mm,    Z =   -227.833  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[289]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -108.594  mm,    Z =   -225.397  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[290]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -105.785  mm,    Z =   -225.397  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[291]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -102.645  mm,    Z =   -223.313  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[292]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -100.305  mm,    Z =   -223.313  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[293]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -98.811  mm,    Z =   -222.084  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[294]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -96.724  mm,    Z =   -222.084  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[295]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -93.569  mm,    Z =   -221.112  mm,
    W =  -170.663 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[296]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -90.469  mm,    Z =   -220.706  mm,
    W =  -172.199 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[297]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -87.404  mm,    Z =   -220.449  mm,
    W =  -173.758 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[298]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -85.392  mm,    Z =   -220.449  mm,
    W =  -173.428 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[299]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -83.821  mm,    Z =   -219.768  mm,
    W =  -170.511 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[300]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -81.262  mm,    Z =   -219.768  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[301]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -78.241  mm,    Z =   -218.854  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[302]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -75.094  mm,    Z =   -218.337  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[303]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -72.477  mm,    Z =   -217.304  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[304]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -70.433  mm,    Z =   -217.304  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[305]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -68.742  mm,    Z =   -216.192  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[306]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -66.755  mm,    Z =   -216.192  mm,
    W =  -171.361 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[307]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -63.675  mm,    Z =   -215.844  mm,
    W =  -172.584 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[308]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -60.584  mm,    Z =   -215.499  mm,
    W =  -171.816 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[309]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -57.506  mm,    Z =   -214.898  mm,
    W =  -171.126 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[310]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -54.459  mm,    Z =   -214.292  mm,
    W =  -170.053 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[311]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -51.280  mm,    Z =   -213.989  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[312]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -48.350  mm,    Z =   -213.124  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[313]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -45.531  mm,    Z =   -212.947  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[314]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -42.495  mm,    Z =   -211.710  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[315]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -40.240  mm,    Z =   -211.710  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[316]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -38.622  mm,    Z =   -209.855  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[317]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -36.242  mm,    Z =   -209.855  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[318]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -33.116  mm,    Z =   -208.329  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[319]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -30.660  mm,    Z =   -208.329  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[320]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -29.153  mm,    Z =   -207.476  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[321]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -27.211  mm,    Z =   -207.476  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[322]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -24.266  mm,    Z =   -206.719  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[323]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -21.376  mm,    Z =   -206.340  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[324]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -18.531  mm,    Z =   -205.416  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[325]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -15.686  mm,    Z =   -205.416  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[326]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -12.841  mm,    Z =   -204.035  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[327]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -9.522  mm,    Z =   -203.000  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[328]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -6.068  mm,    Z =   -201.965  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[329]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -3.274  mm,    Z =   -200.750  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[330]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   -0.416  mm,    Z =   -200.348  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[331]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   2.425  mm,    Z =   -199.543  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[332]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   4.781  mm,    Z =   -199.543  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[333]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   6.199  mm,    Z =   -197.879  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[334]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   8.365  mm,    Z =   -197.879  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[335]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   14.742  mm,    Z =   -196.829  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[336]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   17.391  mm,    Z =   -196.151  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[337]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   19.659  mm,    Z =   -196.151  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[338]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   21.384  mm,    Z =   -193.871  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[339]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   23.682  mm,    Z =   -193.871  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[340]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   26.372  mm,    Z =   -191.980  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[341]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   29.512  mm,    Z =   -191.691  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[342]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   32.637  mm,    Z =   -190.824  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[343]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   34.958  mm,    Z =   -190.824  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[344]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   36.154  mm,    Z =   -189.709  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[345]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   38.503  mm,    Z =   -189.709  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[346]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   41.473  mm,    Z =   -189.177  mm,
    W =  -171.084 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[347]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   44.605  mm,    Z =   -188.884  mm,
    W =  -170.657 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[348]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   47.659  mm,    Z =   -188.005  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[349]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   49.824  mm,    Z =   -188.005  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[350]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   51.368  mm,    Z =   -185.965  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[351]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   53.303  mm,    Z =   -185.965  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[352]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   56.616  mm,    Z =   -184.565  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[353]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   59.172  mm,    Z =   -184.098  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[354]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   60.498  mm,    Z =   -182.796  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[355]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   62.572  mm,    Z =   -182.796  mm,
    W =  -170.065 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[356]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   65.439  mm,    Z =   -182.421  mm,
    W =  -172.835 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[357]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   68.403  mm,    Z =   -182.234  mm,
    W =  -173.592 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[358]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   71.468  mm,    Z =   -181.654  mm,
    W =  -171.029 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[359]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   73.916  mm,    Z =   -181.654  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[360]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   75.663  mm,    Z =   -180.706  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[361]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   77.603  mm,    Z =   -180.706  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[362]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   80.583  mm,    Z =   -180.042  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[363]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   83.314  mm,    Z =   -179.568  mm,
    W =  -170.081 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[364]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   86.362  mm,    Z =   -178.953  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[365]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   89.409  mm,    Z =   -178.749  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[366]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   92.353  mm,    Z =   -177.794  mm,
    W =  -170.871 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[367]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   95.601  mm,    Z =   -177.463  mm,
    W =  -173.719 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[368]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   98.688  mm,    Z =   -177.132  mm,
    W =  -175.617 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[369]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   101.581  mm,    Z =   -176.946  mm,
    W =  -176.278 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[370]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   104.695  mm,    Z =   -176.830  mm,
    W =  -175.996 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[371]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   107.716  mm,    Z =   -176.546  mm,
    W =  -174.645 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[372]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   110.305  mm,    Z =   -176.343  mm,
    W =  -174.595 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[373]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   113.325  mm,    Z =   -175.936  mm,
    W =  -176.366 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[374]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   116.425  mm,    Z =   -175.827  mm,
    W =  -179.283 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[375]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   119.397  mm,    Z =   -175.884  mm,
    W =  -181.379 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[376]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   122.491  mm,    Z =   -176.140  mm,
    W =  -180.954 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[377]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   125.362  mm,    Z =   -176.044  mm,
    W =  -179.906 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[378]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   128.513  mm,    Z =   -175.981  mm,
    W =  -179.170 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[379]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   131.564  mm,    Z =   -175.960  mm,
    W =  -180.654 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[380]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   134.469  mm,    Z =   -175.960  mm,
    W =  -182.318 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[381]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   137.490  mm,    Z =   -176.220  mm,
    W =  -184.120 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[382]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   140.568  mm,    Z =   -176.514  mm,
    W =  -182.925 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[383]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   143.578  mm,    Z =   -176.709  mm,
    W =  -180.884 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[384]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   146.551  mm,    Z =   -176.478  mm,
    W =  -179.199 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[385]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.502  mm,    Y =   148.623  mm,    Z =   -176.478  mm,
    W =  -178.947 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[386]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  529.137  mm,    Y =   209.140  mm,    Z =   -186.478  mm,
    W =  -180.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[387]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  546.235  mm,    Y =   209.140  mm,    Z =   -186.478  mm,
    W =  -180.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[388]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   149.140  mm,    Z =   -176.478  mm,
    W =  -179.608 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[389]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   125.407  mm,    Z =   -176.060  mm,
    W =  -179.714 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[390]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   122.387  mm,    Z =   -176.140  mm,
    W =  -181.038 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[391]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   107.559  mm,    Z =   -176.546  mm,
    W =  -174.839 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[392]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   104.763  mm,    Z =   -176.830  mm,
    W =  -175.797 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[393]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   74.291  mm,    Z =   -181.654  mm,
    W =  -170.141 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[394]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   71.369  mm,    Z =   -181.770  mm,
    W =  -172.023 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[395]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   62.393  mm,    Z =   -182.796  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[396]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   49.642  mm,    Z =   -188.005  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[397]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   47.410  mm,    Z =   -188.005  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[398]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   44.306  mm,    Z =   -189.177  mm,
    W =  -170.560 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[399]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   41.612  mm,    Z =   -189.177  mm,
    W =  -172.123 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[400]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   38.475  mm,    Z =   -189.709  mm,
    W =  -171.101 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[401]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   36.220  mm,    Z =   -189.709  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[402]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   34.868  mm,    Z =   -190.824  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[403]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   32.613  mm,    Z =   -190.824  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[404]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   19.621  mm,    Z =   -196.151  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[405]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   17.344  mm,    Z =   -196.151  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[406]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   14.603  mm,    Z =   -196.874  mm,
    W =  -170.333 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[407]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   11.393  mm,    Z =   -197.396  mm,
    W =  -170.909 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[408]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -3.052  mm,    Z =   -200.750  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[409]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -4.956  mm,    Z =   -201.965  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[410]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -14.511  mm,    Z =   -204.035  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[411]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -21.103  mm,    Z =   -206.340  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[412]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -24.489  mm,    Z =   -206.908  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[413]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -27.853  mm,    Z =   -207.476  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[414]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -30.753  mm,    Z =   -208.329  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[415]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -33.718  mm,    Z =   -208.838  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[416]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -45.816  mm,    Z =   -213.124  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[417]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -48.415  mm,    Z =   -213.124  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[418]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -49.888  mm,    Z =   -213.989  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[419]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -51.815  mm,    Z =   -213.989  mm,
    W =  -170.639 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[420]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -54.727  mm,    Z =   -214.595  mm,
    W =  -170.882 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[421]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -57.725  mm,    Z =   -214.898  mm,
    W =  -171.489 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[422]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -60.554  mm,    Z =   -215.670  mm,
    W =  -172.232 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[423]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -63.381  mm,    Z =   -215.670  mm,
    W =  -173.543 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[424]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -66.296  mm,    Z =   -216.192  mm,
    W =  -171.404 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[425]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -68.864  mm,    Z =   -216.192  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[426]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -70.350  mm,    Z =   -217.304  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[427]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -72.486  mm,    Z =   -217.304  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[428]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -96.266  mm,    Z =   -222.084  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[429]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -98.836  mm,    Z =   -222.084  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[430]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -100.459  mm,    Z =   -223.313  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[431]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -111.393  mm,    Z =   -227.833  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[432]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -115.574  mm,    Z =   -229.723  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[433]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -138.416  mm,    Z =   -234.748  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[434]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -139.716  mm,    Z =   -236.150  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[435]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -141.510  mm,    Z =   -236.150  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[436]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  547.201  mm,    Y =   -143.965  mm,    Z =   -236.150  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[437]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  546.235  mm,    Y =   -216.786  mm,    Z =   -246.150  mm,
    W =  -180.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[438]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  563.333  mm,    Y =   -216.786  mm,    Z =   -247.277  mm,
    W =  -180.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[439]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -147.282  mm,    Z =   -237.277  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[440]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -144.519  mm,    Z =   -236.714  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[441]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -141.632  mm,    Z =   -236.150  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[442]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -138.628  mm,    Z =   -234.748  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[443]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -135.681  mm,    Z =   -234.145  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[444]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -132.158  mm,    Z =   -232.939  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[445]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -129.705  mm,    Z =   -232.939  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[446]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -128.695  mm,    Z =   -231.808  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[447]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -126.674  mm,    Z =   -231.808  mm,
    W =  -170.094 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[448]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -123.643  mm,    Z =   -231.420  mm,
    W =  -171.026 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[449]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -120.575  mm,    Z =   -231.059  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[450]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -117.415  mm,    Z =   -229.723  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[451]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -115.237  mm,    Z =   -229.723  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[452]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -113.789  mm,    Z =   -227.833  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[453]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -111.461  mm,    Z =   -227.833  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[454]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -108.510  mm,    Z =   -225.397  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[455]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -105.596  mm,    Z =   -224.934  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[456]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -102.279  mm,    Z =   -223.313  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[457]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -100.065  mm,    Z =   -223.313  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[458]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -98.755  mm,    Z =   -222.084  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[459]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -90.242  mm,    Z =   -220.669  mm,
    W =  -172.562 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[460]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -87.397  mm,    Z =   -220.449  mm,
    W =  -173.753 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[461]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -85.347  mm,    Z =   -220.449  mm,
    W =  -173.175 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[462]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -83.705  mm,    Z =   -219.768  mm,
    W =  -170.002 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[463]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -81.120  mm,    Z =   -219.768  mm,
    W =  -170.598 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[464]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -78.357  mm,    Z =   -218.854  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[465]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -75.767  mm,    Z =   -218.854  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[466]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -72.866  mm,    Z =   -217.304  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[467]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -70.146  mm,    Z =   -217.304  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[468]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -68.635  mm,    Z =   -216.192  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[469]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -66.688  mm,    Z =   -216.192  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[470]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -63.563  mm,    Z =   -215.670  mm,
    W =  -172.272 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[471]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -60.489  mm,    Z =   -215.413  mm,
    W =  -172.331 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[472]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -57.598  mm,    Z =   -214.898  mm,
    W =  -171.470 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[473]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -54.706  mm,    Z =   -214.595  mm,
    W =  -171.205 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[474]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -51.815  mm,    Z =   -213.989  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[475]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -49.888  mm,    Z =   -213.989  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[476]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -49.888  mm,    Z =   -213.989  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[477]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -48.123  mm,    Z =   -213.124  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[478]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -45.224  mm,    Z =   -212.653  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[479]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -42.502  mm,    Z =   -211.710  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[480]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -40.392  mm,    Z =   -211.710  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[481]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   -38.846  mm,    Z =   -209.855  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[482]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   2.573  mm,    Z =   -199.543  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[483]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   5.011  mm,    Z =   -199.543  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[484]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   6.318  mm,    Z =   -197.879  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[485]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   8.258  mm,    Z =   -197.879  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[486]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   11.304  mm,    Z =   -197.407  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[487]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   14.600  mm,    Z =   -196.874  mm,
    W =  -170.267 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[488]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   17.344  mm,    Z =   -196.151  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[489]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   19.624  mm,    Z =   -196.151  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[490]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   21.437  mm,    Z =   -193.871  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[491]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   23.676  mm,    Z =   -193.871  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[492]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   26.451  mm,    Z =   -191.980  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[493]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   29.504  mm,    Z =   -191.691  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[494]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   32.550  mm,    Z =   -190.824  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[495]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   34.868  mm,    Z =   -190.824  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[496]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   36.220  mm,    Z =   -189.709  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[497]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   38.437  mm,    Z =   -189.709  mm,
    W =  -170.058 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[498]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   41.549  mm,    Z =   -189.177  mm,
    W =  -171.303 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[499]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   44.246  mm,    Z =   -189.177  mm,
    W =  -170.887 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[500]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   47.327  mm,    Z =   -188.005  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[501]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   49.918  mm,    Z =   -188.005  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[502]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   51.191  mm,    Z =   -185.965  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[503]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   53.200  mm,    Z =   -185.965  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[504]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   56.584  mm,    Z =   -184.565  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[505]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   59.172  mm,    Z =   -184.098  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[506]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   60.498  mm,    Z =   -182.796  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[507]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   62.749  mm,    Z =   -182.796  mm,
    W =  -170.008 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[508]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   65.646  mm,    Z =   -182.421  mm,
    W =  -173.118 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[509]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   68.576  mm,    Z =   -182.234  mm,
    W =  -174.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[510]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   71.641  mm,    Z =   -181.654  mm,
    W =  -171.199 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[511]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   74.246  mm,    Z =   -181.654  mm,
    W =  -170.162 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[512]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   75.848  mm,    Z =   -180.706  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[513]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   75.848  mm,    Z =   -180.706  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[514]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   77.443  mm,    Z =   -180.706  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[515]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   80.431  mm,    Z =   -180.137  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[516]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   83.532  mm,    Z =   -179.567  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[517]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   86.361  mm,    Z =   -178.866  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[518]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   89.031  mm,    Z =   -178.749  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[519]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   90.687  mm,    Z =   -177.794  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[520]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   92.689  mm,    Z =   -177.794  mm,
    W =  -171.725 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[521]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   95.485  mm,    Z =   -177.397  mm,
    W =  -173.948 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[522]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   98.654  mm,    Z =   -177.132  mm,
    W =  -175.358 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[523]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   101.645  mm,    Z =   -176.925  mm,
    W =  -176.300 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[524]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   104.582  mm,    Z =   -176.809  mm,
    W =  -175.768 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[525]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   107.432  mm,    Z =   -176.546  mm,
    W =  -174.908 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[526]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   110.260  mm,    Z =   -176.241  mm,
    W =  -174.748 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[527]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   113.582  mm,    Z =   -175.936  mm,
    W =  -176.841 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[528]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   116.585  mm,    Z =   -175.827  mm,
    W =  -179.285 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[529]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   119.587  mm,    Z =   -175.905  mm,
    W =  -181.256 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[530]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   122.590  mm,    Z =   -176.140  mm,
    W =  -181.018 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[531]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   125.389  mm,    Z =   -176.060  mm,
    W =  -179.764 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[532]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   128.192  mm,    Z =   -175.981  mm,
    W =  -179.089 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[533]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   130.979  mm,    Z =   -175.970  mm,
    W =  -179.967 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[534]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   131.449  mm,    Z =   -175.964  mm,
    W =  -180.309 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[535]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   133.102  mm,    Z =   -175.960  mm,
    W =  -180.741 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[536]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  562.610  mm,    Y =   134.463  mm,    Z =   -175.988  mm,
    W =  -182.086 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[537]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  563.333  mm,    Y =   209.140  mm,    Z =   -185.988  mm,
    W =  -180.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[538]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  580.431  mm,    Y =   209.140  mm,    Z =   -185.988  mm,
    W =  -180.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[539]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   134.463  mm,    Z =   -175.988  mm,
    W =  -182.086 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[540]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   133.102  mm,    Z =   -175.960  mm,
    W =  -180.741 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[541]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   131.449  mm,    Z =   -175.964  mm,
    W =  -180.309 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[542]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   130.979  mm,    Z =   -175.970  mm,
    W =  -179.967 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[543]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   128.192  mm,    Z =   -175.981  mm,
    W =  -179.089 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[544]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   125.389  mm,    Z =   -176.060  mm,
    W =  -179.764 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[545]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   122.590  mm,    Z =   -176.140  mm,
    W =  -181.018 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[546]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   119.587  mm,    Z =   -175.905  mm,
    W =  -181.256 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[547]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   116.585  mm,    Z =   -175.827  mm,
    W =  -179.285 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[548]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   113.582  mm,    Z =   -175.936  mm,
    W =  -176.841 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[549]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   110.260  mm,    Z =   -176.241  mm,
    W =  -174.748 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[550]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   107.432  mm,    Z =   -176.546  mm,
    W =  -174.908 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[551]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   104.582  mm,    Z =   -176.809  mm,
    W =  -175.768 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[552]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   101.645  mm,    Z =   -176.925  mm,
    W =  -176.300 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[553]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   98.654  mm,    Z =   -177.132  mm,
    W =  -175.358 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[554]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   95.485  mm,    Z =   -177.397  mm,
    W =  -173.948 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[555]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   92.689  mm,    Z =   -177.794  mm,
    W =  -171.725 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[556]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   90.687  mm,    Z =   -177.794  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[557]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   89.031  mm,    Z =   -178.749  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[558]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   86.361  mm,    Z =   -178.866  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[559]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   83.532  mm,    Z =   -179.567  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[560]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   80.431  mm,    Z =   -180.137  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[561]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   77.443  mm,    Z =   -180.706  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[562]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   75.848  mm,    Z =   -180.706  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[563]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   75.848  mm,    Z =   -180.706  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[564]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   74.246  mm,    Z =   -181.654  mm,
    W =  -170.162 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[565]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   71.641  mm,    Z =   -181.654  mm,
    W =  -171.199 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[566]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   68.576  mm,    Z =   -182.234  mm,
    W =  -174.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[567]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   65.646  mm,    Z =   -182.421  mm,
    W =  -173.118 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[568]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   62.749  mm,    Z =   -182.796  mm,
    W =  -170.008 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[569]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   60.498  mm,    Z =   -182.796  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[570]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   59.172  mm,    Z =   -184.098  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[571]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   56.584  mm,    Z =   -184.565  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[572]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   53.200  mm,    Z =   -185.965  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[573]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   51.191  mm,    Z =   -185.965  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[574]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   49.918  mm,    Z =   -188.005  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[575]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   47.327  mm,    Z =   -188.005  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[576]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   44.246  mm,    Z =   -189.177  mm,
    W =  -170.887 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[577]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   41.549  mm,    Z =   -189.177  mm,
    W =  -171.303 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[578]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   38.437  mm,    Z =   -189.709  mm,
    W =  -170.058 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[579]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   36.220  mm,    Z =   -189.709  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[580]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   34.868  mm,    Z =   -190.824  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[581]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   32.550  mm,    Z =   -190.824  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[582]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   29.504  mm,    Z =   -191.691  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[583]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   26.451  mm,    Z =   -191.980  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[584]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   23.676  mm,    Z =   -193.871  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[585]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   21.437  mm,    Z =   -193.871  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[586]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   19.624  mm,    Z =   -196.151  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[587]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   17.344  mm,    Z =   -196.151  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[588]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   14.600  mm,    Z =   -196.874  mm,
    W =  -170.267 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[589]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   11.304  mm,    Z =   -197.407  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[590]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   8.258  mm,    Z =   -197.879  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[591]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   6.318  mm,    Z =   -197.879  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[592]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   5.011  mm,    Z =   -199.543  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[593]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   2.573  mm,    Z =   -199.543  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[594]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -38.846  mm,    Z =   -209.855  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[595]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -40.392  mm,    Z =   -211.710  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[596]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -42.502  mm,    Z =   -211.710  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[597]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -45.224  mm,    Z =   -212.653  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[598]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -48.123  mm,    Z =   -213.124  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[599]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -49.888  mm,    Z =   -213.989  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[600]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -49.888  mm,    Z =   -213.989  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[601]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -51.815  mm,    Z =   -213.989  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[602]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -54.706  mm,    Z =   -214.595  mm,
    W =  -171.205 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[603]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -57.598  mm,    Z =   -214.898  mm,
    W =  -171.470 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[604]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -60.489  mm,    Z =   -215.413  mm,
    W =  -172.331 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[605]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -63.563  mm,    Z =   -215.670  mm,
    W =  -172.272 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[606]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -66.688  mm,    Z =   -216.192  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[607]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -68.635  mm,    Z =   -216.192  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[608]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -70.146  mm,    Z =   -217.304  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[609]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -72.866  mm,    Z =   -217.304  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[610]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -75.767  mm,    Z =   -218.854  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[611]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -78.357  mm,    Z =   -218.854  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[612]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -81.120  mm,    Z =   -219.768  mm,
    W =  -170.598 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[613]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -83.705  mm,    Z =   -219.768  mm,
    W =  -170.002 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[614]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -85.347  mm,    Z =   -220.449  mm,
    W =  -173.175 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[615]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -87.397  mm,    Z =   -220.449  mm,
    W =  -173.753 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[616]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -90.242  mm,    Z =   -220.669  mm,
    W =  -172.562 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[617]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -98.755  mm,    Z =   -222.084  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[618]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -100.065  mm,    Z =   -223.313  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[619]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -102.279  mm,    Z =   -223.313  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[620]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -105.596  mm,    Z =   -224.934  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[621]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -108.510  mm,    Z =   -225.397  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[622]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -111.461  mm,    Z =   -227.833  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[623]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -113.789  mm,    Z =   -227.833  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[624]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -115.237  mm,    Z =   -229.723  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[625]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -117.415  mm,    Z =   -229.723  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[626]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -120.575  mm,    Z =   -231.059  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[627]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -123.643  mm,    Z =   -231.420  mm,
    W =  -171.026 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[628]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -126.674  mm,    Z =   -231.808  mm,
    W =  -170.094 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[629]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -128.695  mm,    Z =   -231.808  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[630]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -129.705  mm,    Z =   -232.939  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[631]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -132.158  mm,    Z =   -232.939  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[632]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -135.681  mm,    Z =   -234.145  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[633]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -138.628  mm,    Z =   -234.748  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[634]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -141.632  mm,    Z =   -236.150  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[635]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -144.519  mm,    Z =   -236.714  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[636]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  579.708  mm,    Y =   -147.282  mm,    Z =   -237.277  mm,
    W =  -170.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[637]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  580.431  mm,    Y =   -216.786  mm,    Z =   -247.277  mm,
    W =  -180.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[638]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  420.246  mm,    Y =   0.000  mm,    Z =   53.417  mm,
    W =  -180.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
/END
